### ISSUE TITLE
`io::Write` as a `feature`?

### ISSUE THREAD

**Issue by dpc** [whitequark/rust-log_buffer#2]
It would be neat if one could use it as `io::Write`. Obviously that would break `!#[no_sdt]` but maybe hidding it behind a `feature` flag would make it possible?

**Comment by whitequark** [comment]
There's another problem with this: `io::Write` lets you write any sequence of bytes whereas `core::fmt::Write` only permits UTF-8. What are you trying to achieve?

**Comment by dpc** [comment]
What's the problem with that? Underneath it's a `[u8]` anyway?

**Comment by whitequark** [comment]
The problem with that is that I can't return the contents as &str.

**Comment by dpc** [comment]
Can you really right now? How does the library deal with the edge of the circular buffer where half of the bytes of code unit were already overwritten, leaving non valid UTF-8 in the buffer?

**Comment by whitequark** [comment]
Yes, I can (there are even tests for that). And the fact that it exports a safe interface that returns a &str should hint at that.

Internally the way it works is that, since UTF-8 is self-synchronizing, I simply skip all non-leader bytes at the start of the recording in the ring.

**Comment by dpc** [comment]
I see. So, could the `io::Write` version use utf-8 validator for `&str`, and have additional method to just get `&[u8]`? I understand that in `#[no_std]` you don't want to do it, but with stdlib you're getting utf-8 validation from stdlib itself, and it's reasonable cost to pay if someone wants convince of `&str` instead of `&[u8]`.

**Comment by whitequark** [comment]
> So, could the io::Write version use utf-8 validator for &str, and have additional method to just get &[u8]?

Again, what exactly are you trying to achieve? The whole point of this library is having a UTF-8 ring buffer specifically.

**Comment by dpc** [comment]
One user of `slog-rs` have asked if `slog` has a circular logging buffer. So, as slog streams to any `io::Write` I though, why not to just take a circular buffer implementation. So I've found this library, but it does not implement `io::Write`.

**Comment by whitequark** [comment]
That wouldn't work even if it implemented `io::Write`. You would need exclusive access to a `LogBuffer` (`&mut` or owned) in `slog::Streamer` to write logs into it, which leaves no way to extract them. In principle (if you added an `into_inner() -> W` to `slog::Streamer`) you could extract the `LogBuffer`, read it out, and then recreate the streamer, but that would create a race condition.

**Comment by whitequark** [comment]
Also, now that I read it, `slog::Message` simply writes a &str into an `io::Write`. If you changed that to `fmt::Write`, then slog would become usable with `#[no_std]` too, which I think would be useful on its own right! You can currently do that with `log`.

**Comment by dpc** [comment]
Exclusive access can be done with `Mutex+Arc`, or `ArcCell` could swap the buffer atomically when someone wants to read it out. Alternative to `Streamer` could be used too.

I'll look into taking `fmt::Write`, but I'm still using `Arc`s which are not available in core. I'd be very happy if slog could work with `#[no_std]`

**Comment by whitequark** [comment]
> Exclusive access can be done with Mutex+Arc

In the Streamer? Yes, although locking inside a logger seems ill-advised.

> or ArcCell could swap the buffer atomically when someone wants to read it out

This would also clear the log, which is only rarely desired.

> but I'm still using Arcs which are not available in core

`Arc` is in liballoc, which is unfortunately unstable, but it is still a dependency of a large amount of `#[no_std]` crates, so it should be fine to take for now.

**Comment by dpc** [comment]
Well, log records can come from any thread, so I have to deal with it somehow. As long as lock is taken only briefly etc. it should be OK, while people can write their own faster drains for specific purposes. Do you see any good alternatives?

Good to know about `liballoc`. That might work. Thanks!

As `io::Write` is more general purpose I'll leave `Streamer` as is, and just create `FmtStreamer` that takes `W : fmt::Write`, and that would work for whoever needs it, and can be backed by `log_buffer`. When compiled with feature for `#[no_std]` `slog` would not have normal `Streamer` and use `liballoc::Arc`. Sounds like a plan.

**Comment by whitequark** [comment]
> Well, logging can come with any thread, so I have to deal with it somehow. As long as lock is taken only briefly etc. it should be OK, while people can write their own faster drains for specific purposes. Do you see any good alternatives.

Note that Mutex is in std only, and further, actually making a mutex primitive might not be easy or even possible depending on the type of your environment. (For example, the environment I use Rust in has a custom I/O scheduler that simply does not implement mutexes.)

The obvious ways to implement this is a lock-free queue (lossless) or a lock-free ring buffer (lossy). Making LogBuffer itself lock-free would probably not be an option with anything resembling the current implementation.

**Comment by dpc** [comment]
One can always use spinlock like https://github.com/mvdnes/spin-rs, that compiles to NOP on single-core embedded systems etc.

Lock-free queue would be something like `Queue<Vec<u8>>` / `Queue<String>` ? That would require allocation on every `String`/Vec<u8>`, no?

Another approach is to have thread-local buffers that are being written to, and eg. combine them on printouts only etc.

**Comment by whitequark** [comment]
> that compiles to NOP on single-core embedded systems etc.

That can't legally compile to NOP on an embedded system that has preemptive multitasking.

> Lock-free queue would be something like Queue<Vec<u8>> / Queue<String> ? That would require allocation on every String/Vec`, no?

With an arena that allocation could be very cheap. (Really, with an arena this is becoming functionally indistinguishable with a ring buffer...)

> Another approach is to have thread-local Buffers that are being written to.

`#[thread_local]` is special-cased in LLVM for a few major platforms and there is no way to make it work on bare metal unless you are willing to use a patched LLVM build (and even then it is annoying to actually do). So that would work but only if you could inject the thread-localness as a dependency.

**Comment by dpc** [comment]
> That can't legally compile to NOP on an embedded system that has preemptive multitasking.

Yes. Then you need to disable preemption instead, which is cheap.

**Comment by dpc** [comment]
It could almost be pulled of, but I need a `Vec`. Any ideas?

**Comment by whitequark** [comment]
`Vec` is in libcollections, which only depends on liballoc. IMO it makes very little difference whether you depend on liballoc alone or liballoc+libcollections; both are going to be stabilized via much the same process.

**Comment by dpc** [comment]
I did it. Thank you so much! `slog-rs` will now be usable in `#[no_std]`. I still need to implement actual crate implementing circular buffer logging or something like that, but there's nothing difficult about that now.
