### ISSUE TITLE
Spec for improved performance and API

### ISSUE THREAD

**Issue by vitiral** [whitequark/rust-log_buffer#3]
I'm looking at this crate, and I don't see the point of it if it can take `O(n)` for every log. That is a **huge** performance hit, and I think I have a better idea.

To stick with the principle of "log_buffer", where each "log" is a single event, I would make the API something like this:

```
push(&mut self, msg: &str)
get(&self) -> &str
```

Since log mesages are required to be utf8, we can use 0 to denote the end or empty space. Let's say we have the following scenario:

```
// where * is the start and & is the end of the ring
// buf: [ 0 0 0 0 0 0 0*a b 0 c 0&0 0]
buf.push("defg")
// problem: we are pushing 4 bytes but we only have 2
// bytes left
// instead of wrapping (and requiring O(n) to read later),
// let's just leave the end values as 0 and put the new value
// in the front
// So buf: [ d e f g 0&0 0*a b 0 c 0 0 0]
// now a "get" returns entire log messages in O(1) time
assert_eq!(buf.pop(), "ab");
assert_eq!(buf.pop(), "c");
assert_eq!(buf.pop(), "defg");
```

In the end, this will lead to some wasted space at the end of the buffer, but massive performance improvements. Also, it will improve the API for applicatins which are, for instance, trying to queue a log buffer to send over a network. Such applications want to send _one message at a time_, and something like this could be perfect for that.

Without these improvements, I don't see why you would use this over a simple single-element circular bufer.

**Comment by whitequark** [comment]
> I'm looking at this crate, and I don't see the point of it if it can take O(n) for every log.

I don't understand what are you referring to. Are you talking about writing or reading here?

> To stick with the principle of "log_buffer", where each "log" is a single event

I have never considered the concept of events when writing log_buffer. It is explicitly designed for storing a sequence of UTF-8 characters and just that. (In fact I didn't even originally implement the mode that skips the half-overwritten lines, it was just straightforward to do given the other extraction function.)

**Comment by vitiral** [comment]
> I don't understand what are you referring to. Are you talking about writing or reading here?

reading and clearing, according to [your documentation](https://whitequark.github.io/rust-log_buffer/log_buffer/struct.LogBuffer.html)

```
fn clear(&mut self)
...
This function takes O(n) time where n is buffer length.

fn extract(&mut self) -> &str
...
This function takes O(n) time where n is buffer length.
```

> I have never considered the concept of events when writing log_buffer. It is explicitly designed for storing a sequence of UTF-8 characters and just that. 

Without something like "events" or "log-messages" I don't see the benefit of this over a simple single-element ring buffer like [cbuf](https://github.com/dpc/cbuf-rs). In fact, I only see a whole host of disadvantages, like it taking O(n) to read and having a more complex API.

I guess one advantage is the fact that it handles UTF-8 well, which is good. But that is a pretty big performance hit!

I guess the question really is: why would someone want a log buffer? My answer would be: so they can store logs and then later print or send them.

If that is the point, then the API could be improved to do that **as well as** fixing the performance issues.

**Comment by vitiral** [comment]
an even faster API (in my opinion, although I am partial to micro-implementations) is to break up log-events into 2**16 chunks. Then instead of storing the `0`'s that I did, the first two bytes would contain the length of the event.

This would enable `O(1)` reading and clearing of all events, which would be _fast_ :)

**Comment by whitequark** [comment]
> I don't see the benefit of this over a simple single-element ring buffer like cbuf.
> I guess one advantage is the fact that it handles UTF-8

You are exactly right. If not for having to handle strings, a regular ring buffer would be sufficient.

> then the API could be improved to do that

I have absolutely no idea as to what benefits the API you're suggesting provides. But even barring that... from what I can see, you are proposing a scheme which stores borrowed pointers inside the log buffer. How exactly does this work in a case where a) there is no allocator (so no Box<String>) and b) I am trying to log dynamic data, such as via `write!`?

**Comment by vitiral** [comment]
You don't need a memory manager, because you are storing the strings (and their length) in the buffer itself. The buffer would be a rudimentary memory manager (note: I'm currently writing a [defragmenting memory manager for microcontrollers](https://github.com/vitiral/defrag-rs))

When I say "rudimentary" though, I mean it -- it would be very simple. I could create a PR for you that implements the basics.

> b) I am trying to log dynamic data, such as via write!?

This got me thinking, to avoid the wasteful use of memory (and be able to continuously write), you could have `get()` to return `SplitStr` where SplitStr holds reference to two separate `&str`'s but behaves (through indexing, iter, etc) as if there is only one &str. This would be pretty low cost and easy to implement I would think.

As for an API for dynamic writting, a possible API would be:

```
fn log(&mut self) -> Log<&mut self>;

# Log would have the write API, when it was dropped,
# the length written would be stored at the start of it's data
```

I think this could still use some thought though

**Comment by vitiral** [comment]
Let me try to come up with a more complete design spec. I think this is a little scatter brained at the moment.

**Comment by whitequark** [comment]
> The buffer would be a rudimentary memory manager

I am explicitly not interested in this sort of complexity. log_buffer is intended to be write-continuously, read-almost-never. The extraction could be O(n²) for all I know, it doesn't matter.

**Comment by vitiral** [comment]
okay, sounds good
